name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Install Node and Rsync Files
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "mkdir -p ~/app"
          rsync -avz --delete . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/app

      - name: Install dependencies and start app
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd ~/app
            sudo apt-get update
            sudo apt-get install -y nodejs npm
            npm install
            sudo fuser -k 80/tcp || true
            sudo nohup npm start > app.log 2>&1 &
          EOF
